// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/Sadzeih/valcompbot/ent/runtime.go

const (
	Version = "v0.14.2-0.20241021115653-89ad7fa39de1"           // Version of ent codegen.
	Sum     = "h1:MGuPJ6s2UfJHw4yOrRAhHW355Pag5qiE0KGS9dkW4+8=" // Sum of ent codegen.
)
