// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HighlightedCommentsColumns holds the columns for the "highlighted_comments" table.
	HighlightedCommentsColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "comment_id", Type: field.TypeString, Unique: true},
		{Name: "body", Type: field.TypeString},
		{Name: "author", Type: field.TypeString},
		{Name: "flair", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeString},
		{Name: "link", Type: field.TypeString},
		{Name: "author_type", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeTime},
	}
	// HighlightedCommentsTable holds the schema information for the "highlighted_comments" table.
	HighlightedCommentsTable = &schema.Table{
		Name:       "highlighted_comments",
		Columns:    HighlightedCommentsColumns,
		PrimaryKey: []*schema.Column{HighlightedCommentsColumns[0]},
	}
	// PickemsEventsColumns holds the columns for the "pickems_events" table.
	PickemsEventsColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "event_id", Type: field.TypeInt, Nullable: true},
		{Name: "timestamp", Type: field.TypeTime},
	}
	// PickemsEventsTable holds the schema information for the "pickems_events" table.
	PickemsEventsTable = &schema.Table{
		Name:       "pickems_events",
		Columns:    PickemsEventsColumns,
		PrimaryKey: []*schema.Column{PickemsEventsColumns[0]},
	}
	// PinnedCommentsColumns holds the columns for the "pinned_comments" table.
	PinnedCommentsColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "comment_id", Type: field.TypeString, Unique: true},
		{Name: "parent_id", Type: field.TypeString},
	}
	// PinnedCommentsTable holds the schema information for the "pinned_comments" table.
	PinnedCommentsTable = &schema.Table{
		Name:       "pinned_comments",
		Columns:    PinnedCommentsColumns,
		PrimaryKey: []*schema.Column{PinnedCommentsColumns[0]},
	}
	// ScheduledMatchesColumns holds the columns for the "scheduled_matches" table.
	ScheduledMatchesColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "match_id", Type: field.TypeString, Unique: true},
		{Name: "done_at", Type: field.TypeTime, Nullable: true},
		{Name: "posted_at", Type: field.TypeTime, Nullable: true},
	}
	// ScheduledMatchesTable holds the schema information for the "scheduled_matches" table.
	ScheduledMatchesTable = &schema.Table{
		Name:       "scheduled_matches",
		Columns:    ScheduledMatchesColumns,
		PrimaryKey: []*schema.Column{ScheduledMatchesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "scheduledmatch_match_id",
				Unique:  false,
				Columns: []*schema.Column{ScheduledMatchesColumns[1]},
			},
		},
	}
	// TrackedEventsColumns holds the columns for the "tracked_events" table.
	TrackedEventsColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "event_id", Type: field.TypeInt, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// TrackedEventsTable holds the schema information for the "tracked_events" table.
	TrackedEventsTable = &schema.Table{
		Name:       "tracked_events",
		Columns:    TrackedEventsColumns,
		PrimaryKey: []*schema.Column{TrackedEventsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HighlightedCommentsTable,
		PickemsEventsTable,
		PinnedCommentsTable,
		ScheduledMatchesTable,
		TrackedEventsTable,
	}
)

func init() {
}
