// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/Sadzeih/valcompbot/ent/migrate"
	"github.com/google/uuid"

	"github.com/Sadzeih/valcompbot/ent/trackedevent"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// TrackedEvent is the client for interacting with the TrackedEvent builders.
	TrackedEvent *TrackedEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.TrackedEvent = NewTrackedEventClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		TrackedEvent: NewTrackedEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		TrackedEvent: NewTrackedEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		TrackedEvent.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.TrackedEvent.Use(hooks...)
}

// TrackedEventClient is a client for the TrackedEvent schema.
type TrackedEventClient struct {
	config
}

// NewTrackedEventClient returns a client for the TrackedEvent from the given config.
func NewTrackedEventClient(c config) *TrackedEventClient {
	return &TrackedEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `trackedevent.Hooks(f(g(h())))`.
func (c *TrackedEventClient) Use(hooks ...Hook) {
	c.hooks.TrackedEvent = append(c.hooks.TrackedEvent, hooks...)
}

// Create returns a create builder for TrackedEvent.
func (c *TrackedEventClient) Create() *TrackedEventCreate {
	mutation := newTrackedEventMutation(c.config, OpCreate)
	return &TrackedEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TrackedEvent entities.
func (c *TrackedEventClient) CreateBulk(builders ...*TrackedEventCreate) *TrackedEventCreateBulk {
	return &TrackedEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TrackedEvent.
func (c *TrackedEventClient) Update() *TrackedEventUpdate {
	mutation := newTrackedEventMutation(c.config, OpUpdate)
	return &TrackedEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TrackedEventClient) UpdateOne(te *TrackedEvent) *TrackedEventUpdateOne {
	mutation := newTrackedEventMutation(c.config, OpUpdateOne, withTrackedEvent(te))
	return &TrackedEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TrackedEventClient) UpdateOneID(id uuid.UUID) *TrackedEventUpdateOne {
	mutation := newTrackedEventMutation(c.config, OpUpdateOne, withTrackedEventID(id))
	return &TrackedEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TrackedEvent.
func (c *TrackedEventClient) Delete() *TrackedEventDelete {
	mutation := newTrackedEventMutation(c.config, OpDelete)
	return &TrackedEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TrackedEventClient) DeleteOne(te *TrackedEvent) *TrackedEventDeleteOne {
	return c.DeleteOneID(te.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TrackedEventClient) DeleteOneID(id uuid.UUID) *TrackedEventDeleteOne {
	builder := c.Delete().Where(trackedevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TrackedEventDeleteOne{builder}
}

// Query returns a query builder for TrackedEvent.
func (c *TrackedEventClient) Query() *TrackedEventQuery {
	return &TrackedEventQuery{
		config: c.config,
	}
}

// Get returns a TrackedEvent entity by its id.
func (c *TrackedEventClient) Get(ctx context.Context, id uuid.UUID) (*TrackedEvent, error) {
	return c.Query().Where(trackedevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TrackedEventClient) GetX(ctx context.Context, id uuid.UUID) *TrackedEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TrackedEventClient) Hooks() []Hook {
	return c.hooks.TrackedEvent
}
