// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sadzeih/valcompbot/ent/highlightedcomment"
	"github.com/Sadzeih/valcompbot/ent/predicate"
	"github.com/google/uuid"
)

// HighlightedCommentQuery is the builder for querying HighlightedComment entities.
type HighlightedCommentQuery struct {
	config
	ctx        *QueryContext
	order      []highlightedcomment.OrderOption
	inters     []Interceptor
	predicates []predicate.HighlightedComment
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HighlightedCommentQuery builder.
func (hcq *HighlightedCommentQuery) Where(ps ...predicate.HighlightedComment) *HighlightedCommentQuery {
	hcq.predicates = append(hcq.predicates, ps...)
	return hcq
}

// Limit the number of records to be returned by this query.
func (hcq *HighlightedCommentQuery) Limit(limit int) *HighlightedCommentQuery {
	hcq.ctx.Limit = &limit
	return hcq
}

// Offset to start from.
func (hcq *HighlightedCommentQuery) Offset(offset int) *HighlightedCommentQuery {
	hcq.ctx.Offset = &offset
	return hcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hcq *HighlightedCommentQuery) Unique(unique bool) *HighlightedCommentQuery {
	hcq.ctx.Unique = &unique
	return hcq
}

// Order specifies how the records should be ordered.
func (hcq *HighlightedCommentQuery) Order(o ...highlightedcomment.OrderOption) *HighlightedCommentQuery {
	hcq.order = append(hcq.order, o...)
	return hcq
}

// First returns the first HighlightedComment entity from the query.
// Returns a *NotFoundError when no HighlightedComment was found.
func (hcq *HighlightedCommentQuery) First(ctx context.Context) (*HighlightedComment, error) {
	nodes, err := hcq.Limit(1).All(setContextOp(ctx, hcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{highlightedcomment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) FirstX(ctx context.Context) *HighlightedComment {
	node, err := hcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HighlightedComment ID from the query.
// Returns a *NotFoundError when no HighlightedComment ID was found.
func (hcq *HighlightedCommentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = hcq.Limit(1).IDs(setContextOp(ctx, hcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{highlightedcomment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := hcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HighlightedComment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HighlightedComment entity is found.
// Returns a *NotFoundError when no HighlightedComment entities are found.
func (hcq *HighlightedCommentQuery) Only(ctx context.Context) (*HighlightedComment, error) {
	nodes, err := hcq.Limit(2).All(setContextOp(ctx, hcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{highlightedcomment.Label}
	default:
		return nil, &NotSingularError{highlightedcomment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) OnlyX(ctx context.Context) *HighlightedComment {
	node, err := hcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HighlightedComment ID in the query.
// Returns a *NotSingularError when more than one HighlightedComment ID is found.
// Returns a *NotFoundError when no entities are found.
func (hcq *HighlightedCommentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = hcq.Limit(2).IDs(setContextOp(ctx, hcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{highlightedcomment.Label}
	default:
		err = &NotSingularError{highlightedcomment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := hcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HighlightedComments.
func (hcq *HighlightedCommentQuery) All(ctx context.Context) ([]*HighlightedComment, error) {
	ctx = setContextOp(ctx, hcq.ctx, ent.OpQueryAll)
	if err := hcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HighlightedComment, *HighlightedCommentQuery]()
	return withInterceptors[[]*HighlightedComment](ctx, hcq, qr, hcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) AllX(ctx context.Context) []*HighlightedComment {
	nodes, err := hcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HighlightedComment IDs.
func (hcq *HighlightedCommentQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if hcq.ctx.Unique == nil && hcq.path != nil {
		hcq.Unique(true)
	}
	ctx = setContextOp(ctx, hcq.ctx, ent.OpQueryIDs)
	if err = hcq.Select(highlightedcomment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := hcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hcq *HighlightedCommentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hcq.ctx, ent.OpQueryCount)
	if err := hcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hcq, querierCount[*HighlightedCommentQuery](), hcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) CountX(ctx context.Context) int {
	count, err := hcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hcq *HighlightedCommentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hcq.ctx, ent.OpQueryExist)
	switch _, err := hcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hcq *HighlightedCommentQuery) ExistX(ctx context.Context) bool {
	exist, err := hcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HighlightedCommentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hcq *HighlightedCommentQuery) Clone() *HighlightedCommentQuery {
	if hcq == nil {
		return nil
	}
	return &HighlightedCommentQuery{
		config:     hcq.config,
		ctx:        hcq.ctx.Clone(),
		order:      append([]highlightedcomment.OrderOption{}, hcq.order...),
		inters:     append([]Interceptor{}, hcq.inters...),
		predicates: append([]predicate.HighlightedComment{}, hcq.predicates...),
		// clone intermediate query.
		sql:  hcq.sql.Clone(),
		path: hcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CommentID string `json:"comment_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HighlightedComment.Query().
//		GroupBy(highlightedcomment.FieldCommentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hcq *HighlightedCommentQuery) GroupBy(field string, fields ...string) *HighlightedCommentGroupBy {
	hcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HighlightedCommentGroupBy{build: hcq}
	grbuild.flds = &hcq.ctx.Fields
	grbuild.label = highlightedcomment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CommentID string `json:"comment_id,omitempty"`
//	}
//
//	client.HighlightedComment.Query().
//		Select(highlightedcomment.FieldCommentID).
//		Scan(ctx, &v)
func (hcq *HighlightedCommentQuery) Select(fields ...string) *HighlightedCommentSelect {
	hcq.ctx.Fields = append(hcq.ctx.Fields, fields...)
	sbuild := &HighlightedCommentSelect{HighlightedCommentQuery: hcq}
	sbuild.label = highlightedcomment.Label
	sbuild.flds, sbuild.scan = &hcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HighlightedCommentSelect configured with the given aggregations.
func (hcq *HighlightedCommentQuery) Aggregate(fns ...AggregateFunc) *HighlightedCommentSelect {
	return hcq.Select().Aggregate(fns...)
}

func (hcq *HighlightedCommentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hcq); err != nil {
				return err
			}
		}
	}
	for _, f := range hcq.ctx.Fields {
		if !highlightedcomment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hcq.path != nil {
		prev, err := hcq.path(ctx)
		if err != nil {
			return err
		}
		hcq.sql = prev
	}
	return nil
}

func (hcq *HighlightedCommentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HighlightedComment, error) {
	var (
		nodes = []*HighlightedComment{}
		_spec = hcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HighlightedComment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HighlightedComment{config: hcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (hcq *HighlightedCommentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hcq.querySpec()
	_spec.Node.Columns = hcq.ctx.Fields
	if len(hcq.ctx.Fields) > 0 {
		_spec.Unique = hcq.ctx.Unique != nil && *hcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hcq.driver, _spec)
}

func (hcq *HighlightedCommentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(highlightedcomment.Table, highlightedcomment.Columns, sqlgraph.NewFieldSpec(highlightedcomment.FieldID, field.TypeUUID))
	_spec.From = hcq.sql
	if unique := hcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hcq.path != nil {
		_spec.Unique = true
	}
	if fields := hcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, highlightedcomment.FieldID)
		for i := range fields {
			if fields[i] != highlightedcomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hcq *HighlightedCommentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hcq.driver.Dialect())
	t1 := builder.Table(highlightedcomment.Table)
	columns := hcq.ctx.Fields
	if len(columns) == 0 {
		columns = highlightedcomment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hcq.sql != nil {
		selector = hcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hcq.ctx.Unique != nil && *hcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hcq.predicates {
		p(selector)
	}
	for _, p := range hcq.order {
		p(selector)
	}
	if offset := hcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HighlightedCommentGroupBy is the group-by builder for HighlightedComment entities.
type HighlightedCommentGroupBy struct {
	selector
	build *HighlightedCommentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hcgb *HighlightedCommentGroupBy) Aggregate(fns ...AggregateFunc) *HighlightedCommentGroupBy {
	hcgb.fns = append(hcgb.fns, fns...)
	return hcgb
}

// Scan applies the selector query and scans the result into the given value.
func (hcgb *HighlightedCommentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hcgb.build.ctx, ent.OpQueryGroupBy)
	if err := hcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HighlightedCommentQuery, *HighlightedCommentGroupBy](ctx, hcgb.build, hcgb, hcgb.build.inters, v)
}

func (hcgb *HighlightedCommentGroupBy) sqlScan(ctx context.Context, root *HighlightedCommentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hcgb.fns))
	for _, fn := range hcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hcgb.flds)+len(hcgb.fns))
		for _, f := range *hcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HighlightedCommentSelect is the builder for selecting fields of HighlightedComment entities.
type HighlightedCommentSelect struct {
	*HighlightedCommentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hcs *HighlightedCommentSelect) Aggregate(fns ...AggregateFunc) *HighlightedCommentSelect {
	hcs.fns = append(hcs.fns, fns...)
	return hcs
}

// Scan applies the selector query and scans the result into the given value.
func (hcs *HighlightedCommentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hcs.ctx, ent.OpQuerySelect)
	if err := hcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HighlightedCommentQuery, *HighlightedCommentSelect](ctx, hcs.HighlightedCommentQuery, hcs, hcs.inters, v)
}

func (hcs *HighlightedCommentSelect) sqlScan(ctx context.Context, root *HighlightedCommentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hcs.fns))
	for _, fn := range hcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
