// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sadzeih/valcompbot/ent/highlightedcomment"
	"github.com/Sadzeih/valcompbot/ent/predicate"
)

// HighlightedCommentDelete is the builder for deleting a HighlightedComment entity.
type HighlightedCommentDelete struct {
	config
	hooks    []Hook
	mutation *HighlightedCommentMutation
}

// Where appends a list predicates to the HighlightedCommentDelete builder.
func (hcd *HighlightedCommentDelete) Where(ps ...predicate.HighlightedComment) *HighlightedCommentDelete {
	hcd.mutation.Where(ps...)
	return hcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hcd *HighlightedCommentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, hcd.sqlExec, hcd.mutation, hcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (hcd *HighlightedCommentDelete) ExecX(ctx context.Context) int {
	n, err := hcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hcd *HighlightedCommentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(highlightedcomment.Table, sqlgraph.NewFieldSpec(highlightedcomment.FieldID, field.TypeUUID))
	if ps := hcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, hcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	hcd.mutation.done = true
	return affected, err
}

// HighlightedCommentDeleteOne is the builder for deleting a single HighlightedComment entity.
type HighlightedCommentDeleteOne struct {
	hcd *HighlightedCommentDelete
}

// Where appends a list predicates to the HighlightedCommentDelete builder.
func (hcdo *HighlightedCommentDeleteOne) Where(ps ...predicate.HighlightedComment) *HighlightedCommentDeleteOne {
	hcdo.hcd.mutation.Where(ps...)
	return hcdo
}

// Exec executes the deletion query.
func (hcdo *HighlightedCommentDeleteOne) Exec(ctx context.Context) error {
	n, err := hcdo.hcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{highlightedcomment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hcdo *HighlightedCommentDeleteOne) ExecX(ctx context.Context) {
	if err := hcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
