// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sadzeih/valcompbot/ent/pickemsevent"
	"github.com/Sadzeih/valcompbot/ent/predicate"
	"github.com/google/uuid"
)

// PickemsEventQuery is the builder for querying PickemsEvent entities.
type PickemsEventQuery struct {
	config
	ctx        *QueryContext
	order      []pickemsevent.OrderOption
	inters     []Interceptor
	predicates []predicate.PickemsEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PickemsEventQuery builder.
func (peq *PickemsEventQuery) Where(ps ...predicate.PickemsEvent) *PickemsEventQuery {
	peq.predicates = append(peq.predicates, ps...)
	return peq
}

// Limit the number of records to be returned by this query.
func (peq *PickemsEventQuery) Limit(limit int) *PickemsEventQuery {
	peq.ctx.Limit = &limit
	return peq
}

// Offset to start from.
func (peq *PickemsEventQuery) Offset(offset int) *PickemsEventQuery {
	peq.ctx.Offset = &offset
	return peq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (peq *PickemsEventQuery) Unique(unique bool) *PickemsEventQuery {
	peq.ctx.Unique = &unique
	return peq
}

// Order specifies how the records should be ordered.
func (peq *PickemsEventQuery) Order(o ...pickemsevent.OrderOption) *PickemsEventQuery {
	peq.order = append(peq.order, o...)
	return peq
}

// First returns the first PickemsEvent entity from the query.
// Returns a *NotFoundError when no PickemsEvent was found.
func (peq *PickemsEventQuery) First(ctx context.Context) (*PickemsEvent, error) {
	nodes, err := peq.Limit(1).All(setContextOp(ctx, peq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pickemsevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (peq *PickemsEventQuery) FirstX(ctx context.Context) *PickemsEvent {
	node, err := peq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PickemsEvent ID from the query.
// Returns a *NotFoundError when no PickemsEvent ID was found.
func (peq *PickemsEventQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = peq.Limit(1).IDs(setContextOp(ctx, peq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pickemsevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (peq *PickemsEventQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := peq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PickemsEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PickemsEvent entity is found.
// Returns a *NotFoundError when no PickemsEvent entities are found.
func (peq *PickemsEventQuery) Only(ctx context.Context) (*PickemsEvent, error) {
	nodes, err := peq.Limit(2).All(setContextOp(ctx, peq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pickemsevent.Label}
	default:
		return nil, &NotSingularError{pickemsevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (peq *PickemsEventQuery) OnlyX(ctx context.Context) *PickemsEvent {
	node, err := peq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PickemsEvent ID in the query.
// Returns a *NotSingularError when more than one PickemsEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (peq *PickemsEventQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = peq.Limit(2).IDs(setContextOp(ctx, peq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pickemsevent.Label}
	default:
		err = &NotSingularError{pickemsevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (peq *PickemsEventQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := peq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PickemsEvents.
func (peq *PickemsEventQuery) All(ctx context.Context) ([]*PickemsEvent, error) {
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryAll)
	if err := peq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PickemsEvent, *PickemsEventQuery]()
	return withInterceptors[[]*PickemsEvent](ctx, peq, qr, peq.inters)
}

// AllX is like All, but panics if an error occurs.
func (peq *PickemsEventQuery) AllX(ctx context.Context) []*PickemsEvent {
	nodes, err := peq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PickemsEvent IDs.
func (peq *PickemsEventQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if peq.ctx.Unique == nil && peq.path != nil {
		peq.Unique(true)
	}
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryIDs)
	if err = peq.Select(pickemsevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (peq *PickemsEventQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := peq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (peq *PickemsEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryCount)
	if err := peq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, peq, querierCount[*PickemsEventQuery](), peq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (peq *PickemsEventQuery) CountX(ctx context.Context) int {
	count, err := peq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (peq *PickemsEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, peq.ctx, ent.OpQueryExist)
	switch _, err := peq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (peq *PickemsEventQuery) ExistX(ctx context.Context) bool {
	exist, err := peq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PickemsEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (peq *PickemsEventQuery) Clone() *PickemsEventQuery {
	if peq == nil {
		return nil
	}
	return &PickemsEventQuery{
		config:     peq.config,
		ctx:        peq.ctx.Clone(),
		order:      append([]pickemsevent.OrderOption{}, peq.order...),
		inters:     append([]Interceptor{}, peq.inters...),
		predicates: append([]predicate.PickemsEvent{}, peq.predicates...),
		// clone intermediate query.
		sql:  peq.sql.Clone(),
		path: peq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PickemsEvent.Query().
//		GroupBy(pickemsevent.FieldEventID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (peq *PickemsEventQuery) GroupBy(field string, fields ...string) *PickemsEventGroupBy {
	peq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PickemsEventGroupBy{build: peq}
	grbuild.flds = &peq.ctx.Fields
	grbuild.label = pickemsevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//	}
//
//	client.PickemsEvent.Query().
//		Select(pickemsevent.FieldEventID).
//		Scan(ctx, &v)
func (peq *PickemsEventQuery) Select(fields ...string) *PickemsEventSelect {
	peq.ctx.Fields = append(peq.ctx.Fields, fields...)
	sbuild := &PickemsEventSelect{PickemsEventQuery: peq}
	sbuild.label = pickemsevent.Label
	sbuild.flds, sbuild.scan = &peq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PickemsEventSelect configured with the given aggregations.
func (peq *PickemsEventQuery) Aggregate(fns ...AggregateFunc) *PickemsEventSelect {
	return peq.Select().Aggregate(fns...)
}

func (peq *PickemsEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range peq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, peq); err != nil {
				return err
			}
		}
	}
	for _, f := range peq.ctx.Fields {
		if !pickemsevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if peq.path != nil {
		prev, err := peq.path(ctx)
		if err != nil {
			return err
		}
		peq.sql = prev
	}
	return nil
}

func (peq *PickemsEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PickemsEvent, error) {
	var (
		nodes = []*PickemsEvent{}
		_spec = peq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PickemsEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PickemsEvent{config: peq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, peq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (peq *PickemsEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := peq.querySpec()
	_spec.Node.Columns = peq.ctx.Fields
	if len(peq.ctx.Fields) > 0 {
		_spec.Unique = peq.ctx.Unique != nil && *peq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, peq.driver, _spec)
}

func (peq *PickemsEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pickemsevent.Table, pickemsevent.Columns, sqlgraph.NewFieldSpec(pickemsevent.FieldID, field.TypeUUID))
	_spec.From = peq.sql
	if unique := peq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if peq.path != nil {
		_spec.Unique = true
	}
	if fields := peq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pickemsevent.FieldID)
		for i := range fields {
			if fields[i] != pickemsevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := peq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := peq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := peq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := peq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (peq *PickemsEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(peq.driver.Dialect())
	t1 := builder.Table(pickemsevent.Table)
	columns := peq.ctx.Fields
	if len(columns) == 0 {
		columns = pickemsevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if peq.sql != nil {
		selector = peq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if peq.ctx.Unique != nil && *peq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range peq.predicates {
		p(selector)
	}
	for _, p := range peq.order {
		p(selector)
	}
	if offset := peq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := peq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PickemsEventGroupBy is the group-by builder for PickemsEvent entities.
type PickemsEventGroupBy struct {
	selector
	build *PickemsEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pegb *PickemsEventGroupBy) Aggregate(fns ...AggregateFunc) *PickemsEventGroupBy {
	pegb.fns = append(pegb.fns, fns...)
	return pegb
}

// Scan applies the selector query and scans the result into the given value.
func (pegb *PickemsEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pegb.build.ctx, ent.OpQueryGroupBy)
	if err := pegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PickemsEventQuery, *PickemsEventGroupBy](ctx, pegb.build, pegb, pegb.build.inters, v)
}

func (pegb *PickemsEventGroupBy) sqlScan(ctx context.Context, root *PickemsEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pegb.fns))
	for _, fn := range pegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pegb.flds)+len(pegb.fns))
		for _, f := range *pegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PickemsEventSelect is the builder for selecting fields of PickemsEvent entities.
type PickemsEventSelect struct {
	*PickemsEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pes *PickemsEventSelect) Aggregate(fns ...AggregateFunc) *PickemsEventSelect {
	pes.fns = append(pes.fns, fns...)
	return pes
}

// Scan applies the selector query and scans the result into the given value.
func (pes *PickemsEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pes.ctx, ent.OpQuerySelect)
	if err := pes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PickemsEventQuery, *PickemsEventSelect](ctx, pes.PickemsEventQuery, pes, pes.inters, v)
}

func (pes *PickemsEventSelect) sqlScan(ctx context.Context, root *PickemsEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pes.fns))
	for _, fn := range pes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
