// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/Sadzeih/valcompbot/ent/schema"
	"github.com/Sadzeih/valcompbot/ent/trackedevent"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	trackedeventFields := schema.TrackedEvent{}.Fields()
	_ = trackedeventFields
	// trackedeventDescID is the schema descriptor for id field.
	trackedeventDescID := trackedeventFields[0].Descriptor()
	// trackedevent.DefaultID holds the default value on creation for the id field.
	trackedevent.DefaultID = trackedeventDescID.Default.(func() uuid.UUID)
}
