// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sadzeih/valcompbot/ent/predicate"
	"github.com/Sadzeih/valcompbot/ent/scheduledmatch"
	"github.com/google/uuid"
)

// ScheduledMatchQuery is the builder for querying ScheduledMatch entities.
type ScheduledMatchQuery struct {
	config
	ctx        *QueryContext
	order      []scheduledmatch.OrderOption
	inters     []Interceptor
	predicates []predicate.ScheduledMatch
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScheduledMatchQuery builder.
func (smq *ScheduledMatchQuery) Where(ps ...predicate.ScheduledMatch) *ScheduledMatchQuery {
	smq.predicates = append(smq.predicates, ps...)
	return smq
}

// Limit the number of records to be returned by this query.
func (smq *ScheduledMatchQuery) Limit(limit int) *ScheduledMatchQuery {
	smq.ctx.Limit = &limit
	return smq
}

// Offset to start from.
func (smq *ScheduledMatchQuery) Offset(offset int) *ScheduledMatchQuery {
	smq.ctx.Offset = &offset
	return smq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smq *ScheduledMatchQuery) Unique(unique bool) *ScheduledMatchQuery {
	smq.ctx.Unique = &unique
	return smq
}

// Order specifies how the records should be ordered.
func (smq *ScheduledMatchQuery) Order(o ...scheduledmatch.OrderOption) *ScheduledMatchQuery {
	smq.order = append(smq.order, o...)
	return smq
}

// First returns the first ScheduledMatch entity from the query.
// Returns a *NotFoundError when no ScheduledMatch was found.
func (smq *ScheduledMatchQuery) First(ctx context.Context) (*ScheduledMatch, error) {
	nodes, err := smq.Limit(1).All(setContextOp(ctx, smq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scheduledmatch.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smq *ScheduledMatchQuery) FirstX(ctx context.Context) *ScheduledMatch {
	node, err := smq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScheduledMatch ID from the query.
// Returns a *NotFoundError when no ScheduledMatch ID was found.
func (smq *ScheduledMatchQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = smq.Limit(1).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scheduledmatch.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smq *ScheduledMatchQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := smq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScheduledMatch entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScheduledMatch entity is found.
// Returns a *NotFoundError when no ScheduledMatch entities are found.
func (smq *ScheduledMatchQuery) Only(ctx context.Context) (*ScheduledMatch, error) {
	nodes, err := smq.Limit(2).All(setContextOp(ctx, smq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scheduledmatch.Label}
	default:
		return nil, &NotSingularError{scheduledmatch.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smq *ScheduledMatchQuery) OnlyX(ctx context.Context) *ScheduledMatch {
	node, err := smq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScheduledMatch ID in the query.
// Returns a *NotSingularError when more than one ScheduledMatch ID is found.
// Returns a *NotFoundError when no entities are found.
func (smq *ScheduledMatchQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = smq.Limit(2).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scheduledmatch.Label}
	default:
		err = &NotSingularError{scheduledmatch.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smq *ScheduledMatchQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := smq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScheduledMatches.
func (smq *ScheduledMatchQuery) All(ctx context.Context) ([]*ScheduledMatch, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryAll)
	if err := smq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScheduledMatch, *ScheduledMatchQuery]()
	return withInterceptors[[]*ScheduledMatch](ctx, smq, qr, smq.inters)
}

// AllX is like All, but panics if an error occurs.
func (smq *ScheduledMatchQuery) AllX(ctx context.Context) []*ScheduledMatch {
	nodes, err := smq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScheduledMatch IDs.
func (smq *ScheduledMatchQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if smq.ctx.Unique == nil && smq.path != nil {
		smq.Unique(true)
	}
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryIDs)
	if err = smq.Select(scheduledmatch.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smq *ScheduledMatchQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := smq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smq *ScheduledMatchQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryCount)
	if err := smq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, smq, querierCount[*ScheduledMatchQuery](), smq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (smq *ScheduledMatchQuery) CountX(ctx context.Context) int {
	count, err := smq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smq *ScheduledMatchQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryExist)
	switch _, err := smq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (smq *ScheduledMatchQuery) ExistX(ctx context.Context) bool {
	exist, err := smq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScheduledMatchQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smq *ScheduledMatchQuery) Clone() *ScheduledMatchQuery {
	if smq == nil {
		return nil
	}
	return &ScheduledMatchQuery{
		config:     smq.config,
		ctx:        smq.ctx.Clone(),
		order:      append([]scheduledmatch.OrderOption{}, smq.order...),
		inters:     append([]Interceptor{}, smq.inters...),
		predicates: append([]predicate.ScheduledMatch{}, smq.predicates...),
		// clone intermediate query.
		sql:  smq.sql.Clone(),
		path: smq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MatchID string `json:"match_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScheduledMatch.Query().
//		GroupBy(scheduledmatch.FieldMatchID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (smq *ScheduledMatchQuery) GroupBy(field string, fields ...string) *ScheduledMatchGroupBy {
	smq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScheduledMatchGroupBy{build: smq}
	grbuild.flds = &smq.ctx.Fields
	grbuild.label = scheduledmatch.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MatchID string `json:"match_id,omitempty"`
//	}
//
//	client.ScheduledMatch.Query().
//		Select(scheduledmatch.FieldMatchID).
//		Scan(ctx, &v)
func (smq *ScheduledMatchQuery) Select(fields ...string) *ScheduledMatchSelect {
	smq.ctx.Fields = append(smq.ctx.Fields, fields...)
	sbuild := &ScheduledMatchSelect{ScheduledMatchQuery: smq}
	sbuild.label = scheduledmatch.Label
	sbuild.flds, sbuild.scan = &smq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScheduledMatchSelect configured with the given aggregations.
func (smq *ScheduledMatchQuery) Aggregate(fns ...AggregateFunc) *ScheduledMatchSelect {
	return smq.Select().Aggregate(fns...)
}

func (smq *ScheduledMatchQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range smq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, smq); err != nil {
				return err
			}
		}
	}
	for _, f := range smq.ctx.Fields {
		if !scheduledmatch.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smq.path != nil {
		prev, err := smq.path(ctx)
		if err != nil {
			return err
		}
		smq.sql = prev
	}
	return nil
}

func (smq *ScheduledMatchQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScheduledMatch, error) {
	var (
		nodes = []*ScheduledMatch{}
		_spec = smq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScheduledMatch).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScheduledMatch{config: smq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (smq *ScheduledMatchQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smq.querySpec()
	_spec.Node.Columns = smq.ctx.Fields
	if len(smq.ctx.Fields) > 0 {
		_spec.Unique = smq.ctx.Unique != nil && *smq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, smq.driver, _spec)
}

func (smq *ScheduledMatchQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scheduledmatch.Table, scheduledmatch.Columns, sqlgraph.NewFieldSpec(scheduledmatch.FieldID, field.TypeUUID))
	_spec.From = smq.sql
	if unique := smq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if smq.path != nil {
		_spec.Unique = true
	}
	if fields := smq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scheduledmatch.FieldID)
		for i := range fields {
			if fields[i] != scheduledmatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := smq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smq *ScheduledMatchQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smq.driver.Dialect())
	t1 := builder.Table(scheduledmatch.Table)
	columns := smq.ctx.Fields
	if len(columns) == 0 {
		columns = scheduledmatch.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smq.sql != nil {
		selector = smq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smq.ctx.Unique != nil && *smq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range smq.predicates {
		p(selector)
	}
	for _, p := range smq.order {
		p(selector)
	}
	if offset := smq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScheduledMatchGroupBy is the group-by builder for ScheduledMatch entities.
type ScheduledMatchGroupBy struct {
	selector
	build *ScheduledMatchQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smgb *ScheduledMatchGroupBy) Aggregate(fns ...AggregateFunc) *ScheduledMatchGroupBy {
	smgb.fns = append(smgb.fns, fns...)
	return smgb
}

// Scan applies the selector query and scans the result into the given value.
func (smgb *ScheduledMatchGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, smgb.build.ctx, ent.OpQueryGroupBy)
	if err := smgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScheduledMatchQuery, *ScheduledMatchGroupBy](ctx, smgb.build, smgb, smgb.build.inters, v)
}

func (smgb *ScheduledMatchGroupBy) sqlScan(ctx context.Context, root *ScheduledMatchQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(smgb.fns))
	for _, fn := range smgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*smgb.flds)+len(smgb.fns))
		for _, f := range *smgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*smgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScheduledMatchSelect is the builder for selecting fields of ScheduledMatch entities.
type ScheduledMatchSelect struct {
	*ScheduledMatchQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sms *ScheduledMatchSelect) Aggregate(fns ...AggregateFunc) *ScheduledMatchSelect {
	sms.fns = append(sms.fns, fns...)
	return sms
}

// Scan applies the selector query and scans the result into the given value.
func (sms *ScheduledMatchSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sms.ctx, ent.OpQuerySelect)
	if err := sms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScheduledMatchQuery, *ScheduledMatchSelect](ctx, sms.ScheduledMatchQuery, sms, sms.inters, v)
}

func (sms *ScheduledMatchSelect) sqlScan(ctx context.Context, root *ScheduledMatchQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sms.fns))
	for _, fn := range sms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
