// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sadzeih/valcompbot/ent/predicate"
	"github.com/Sadzeih/valcompbot/ent/trackedevent"
	"github.com/google/uuid"
)

// TrackedEventQuery is the builder for querying TrackedEvent entities.
type TrackedEventQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TrackedEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrackedEventQuery builder.
func (teq *TrackedEventQuery) Where(ps ...predicate.TrackedEvent) *TrackedEventQuery {
	teq.predicates = append(teq.predicates, ps...)
	return teq
}

// Limit adds a limit step to the query.
func (teq *TrackedEventQuery) Limit(limit int) *TrackedEventQuery {
	teq.limit = &limit
	return teq
}

// Offset adds an offset step to the query.
func (teq *TrackedEventQuery) Offset(offset int) *TrackedEventQuery {
	teq.offset = &offset
	return teq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (teq *TrackedEventQuery) Unique(unique bool) *TrackedEventQuery {
	teq.unique = &unique
	return teq
}

// Order adds an order step to the query.
func (teq *TrackedEventQuery) Order(o ...OrderFunc) *TrackedEventQuery {
	teq.order = append(teq.order, o...)
	return teq
}

// First returns the first TrackedEvent entity from the query.
// Returns a *NotFoundError when no TrackedEvent was found.
func (teq *TrackedEventQuery) First(ctx context.Context) (*TrackedEvent, error) {
	nodes, err := teq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trackedevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (teq *TrackedEventQuery) FirstX(ctx context.Context) *TrackedEvent {
	node, err := teq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TrackedEvent ID from the query.
// Returns a *NotFoundError when no TrackedEvent ID was found.
func (teq *TrackedEventQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = teq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trackedevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (teq *TrackedEventQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := teq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TrackedEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TrackedEvent entity is found.
// Returns a *NotFoundError when no TrackedEvent entities are found.
func (teq *TrackedEventQuery) Only(ctx context.Context) (*TrackedEvent, error) {
	nodes, err := teq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trackedevent.Label}
	default:
		return nil, &NotSingularError{trackedevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (teq *TrackedEventQuery) OnlyX(ctx context.Context) *TrackedEvent {
	node, err := teq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TrackedEvent ID in the query.
// Returns a *NotSingularError when more than one TrackedEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (teq *TrackedEventQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = teq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = &NotSingularError{trackedevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (teq *TrackedEventQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := teq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TrackedEvents.
func (teq *TrackedEventQuery) All(ctx context.Context) ([]*TrackedEvent, error) {
	if err := teq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return teq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (teq *TrackedEventQuery) AllX(ctx context.Context) []*TrackedEvent {
	nodes, err := teq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TrackedEvent IDs.
func (teq *TrackedEventQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := teq.Select(trackedevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (teq *TrackedEventQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := teq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (teq *TrackedEventQuery) Count(ctx context.Context) (int, error) {
	if err := teq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return teq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (teq *TrackedEventQuery) CountX(ctx context.Context) int {
	count, err := teq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (teq *TrackedEventQuery) Exist(ctx context.Context) (bool, error) {
	if err := teq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return teq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (teq *TrackedEventQuery) ExistX(ctx context.Context) bool {
	exist, err := teq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrackedEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (teq *TrackedEventQuery) Clone() *TrackedEventQuery {
	if teq == nil {
		return nil
	}
	return &TrackedEventQuery{
		config:     teq.config,
		limit:      teq.limit,
		offset:     teq.offset,
		order:      append([]OrderFunc{}, teq.order...),
		predicates: append([]predicate.TrackedEvent{}, teq.predicates...),
		// clone intermediate query.
		sql:    teq.sql.Clone(),
		path:   teq.path,
		unique: teq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TrackedEvent.Query().
//		GroupBy(trackedevent.FieldEventID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (teq *TrackedEventQuery) GroupBy(field string, fields ...string) *TrackedEventGroupBy {
	group := &TrackedEventGroupBy{config: teq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := teq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return teq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//	}
//
//	client.TrackedEvent.Query().
//		Select(trackedevent.FieldEventID).
//		Scan(ctx, &v)
//
func (teq *TrackedEventQuery) Select(fields ...string) *TrackedEventSelect {
	teq.fields = append(teq.fields, fields...)
	return &TrackedEventSelect{TrackedEventQuery: teq}
}

func (teq *TrackedEventQuery) prepareQuery(ctx context.Context) error {
	for _, f := range teq.fields {
		if !trackedevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if teq.path != nil {
		prev, err := teq.path(ctx)
		if err != nil {
			return err
		}
		teq.sql = prev
	}
	return nil
}

func (teq *TrackedEventQuery) sqlAll(ctx context.Context) ([]*TrackedEvent, error) {
	var (
		nodes = []*TrackedEvent{}
		_spec = teq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TrackedEvent{config: teq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, teq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (teq *TrackedEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := teq.querySpec()
	_spec.Node.Columns = teq.fields
	if len(teq.fields) > 0 {
		_spec.Unique = teq.unique != nil && *teq.unique
	}
	return sqlgraph.CountNodes(ctx, teq.driver, _spec)
}

func (teq *TrackedEventQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := teq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (teq *TrackedEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   trackedevent.Table,
			Columns: trackedevent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: trackedevent.FieldID,
			},
		},
		From:   teq.sql,
		Unique: true,
	}
	if unique := teq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := teq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trackedevent.FieldID)
		for i := range fields {
			if fields[i] != trackedevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := teq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := teq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := teq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := teq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (teq *TrackedEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(teq.driver.Dialect())
	t1 := builder.Table(trackedevent.Table)
	columns := teq.fields
	if len(columns) == 0 {
		columns = trackedevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if teq.sql != nil {
		selector = teq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if teq.unique != nil && *teq.unique {
		selector.Distinct()
	}
	for _, p := range teq.predicates {
		p(selector)
	}
	for _, p := range teq.order {
		p(selector)
	}
	if offset := teq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := teq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrackedEventGroupBy is the group-by builder for TrackedEvent entities.
type TrackedEventGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tegb *TrackedEventGroupBy) Aggregate(fns ...AggregateFunc) *TrackedEventGroupBy {
	tegb.fns = append(tegb.fns, fns...)
	return tegb
}

// Scan applies the group-by query and scans the result into the given value.
func (tegb *TrackedEventGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tegb.path(ctx)
	if err != nil {
		return err
	}
	tegb.sql = query
	return tegb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tegb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tegb.fields) > 1 {
		return nil, errors.New("ent: TrackedEventGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) StringsX(ctx context.Context) []string {
	v, err := tegb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tegb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) StringX(ctx context.Context) string {
	v, err := tegb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tegb.fields) > 1 {
		return nil, errors.New("ent: TrackedEventGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) IntsX(ctx context.Context) []int {
	v, err := tegb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tegb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) IntX(ctx context.Context) int {
	v, err := tegb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tegb.fields) > 1 {
		return nil, errors.New("ent: TrackedEventGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tegb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tegb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tegb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tegb.fields) > 1 {
		return nil, errors.New("ent: TrackedEventGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tegb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tegb *TrackedEventGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tegb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tegb *TrackedEventGroupBy) BoolX(ctx context.Context) bool {
	v, err := tegb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tegb *TrackedEventGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tegb.fields {
		if !trackedevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tegb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tegb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tegb *TrackedEventGroupBy) sqlQuery() *sql.Selector {
	selector := tegb.sql.Select()
	aggregation := make([]string, 0, len(tegb.fns))
	for _, fn := range tegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tegb.fields)+len(tegb.fns))
		for _, f := range tegb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tegb.fields...)...)
}

// TrackedEventSelect is the builder for selecting fields of TrackedEvent entities.
type TrackedEventSelect struct {
	*TrackedEventQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tes *TrackedEventSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tes.prepareQuery(ctx); err != nil {
		return err
	}
	tes.sql = tes.TrackedEventQuery.sqlQuery(ctx)
	return tes.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tes *TrackedEventSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tes.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tes.fields) > 1 {
		return nil, errors.New("ent: TrackedEventSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tes *TrackedEventSelect) StringsX(ctx context.Context) []string {
	v, err := tes.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tes.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tes *TrackedEventSelect) StringX(ctx context.Context) string {
	v, err := tes.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tes.fields) > 1 {
		return nil, errors.New("ent: TrackedEventSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tes *TrackedEventSelect) IntsX(ctx context.Context) []int {
	v, err := tes.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tes.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tes *TrackedEventSelect) IntX(ctx context.Context) int {
	v, err := tes.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tes.fields) > 1 {
		return nil, errors.New("ent: TrackedEventSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tes *TrackedEventSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tes.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tes.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tes *TrackedEventSelect) Float64X(ctx context.Context) float64 {
	v, err := tes.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tes.fields) > 1 {
		return nil, errors.New("ent: TrackedEventSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tes *TrackedEventSelect) BoolsX(ctx context.Context) []bool {
	v, err := tes.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tes *TrackedEventSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tes.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trackedevent.Label}
	default:
		err = fmt.Errorf("ent: TrackedEventSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tes *TrackedEventSelect) BoolX(ctx context.Context) bool {
	v, err := tes.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tes *TrackedEventSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tes.sql.Query()
	if err := tes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
