// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sadzeih/valcompbot/ent/trackedevent"
	"github.com/google/uuid"
)

// TrackedEventCreate is the builder for creating a TrackedEvent entity.
type TrackedEventCreate struct {
	config
	mutation *TrackedEventMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (tec *TrackedEventCreate) SetEventID(i int) *TrackedEventCreate {
	tec.mutation.SetEventID(i)
	return tec
}

// SetName sets the "name" field.
func (tec *TrackedEventCreate) SetName(s string) *TrackedEventCreate {
	tec.mutation.SetName(s)
	return tec
}

// SetID sets the "id" field.
func (tec *TrackedEventCreate) SetID(u uuid.UUID) *TrackedEventCreate {
	tec.mutation.SetID(u)
	return tec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tec *TrackedEventCreate) SetNillableID(u *uuid.UUID) *TrackedEventCreate {
	if u != nil {
		tec.SetID(*u)
	}
	return tec
}

// Mutation returns the TrackedEventMutation object of the builder.
func (tec *TrackedEventCreate) Mutation() *TrackedEventMutation {
	return tec.mutation
}

// Save creates the TrackedEvent in the database.
func (tec *TrackedEventCreate) Save(ctx context.Context) (*TrackedEvent, error) {
	tec.defaults()
	return withHooks(ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TrackedEventCreate) SaveX(ctx context.Context) *TrackedEvent {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TrackedEventCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TrackedEventCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tec *TrackedEventCreate) defaults() {
	if _, ok := tec.mutation.ID(); !ok {
		v := trackedevent.DefaultID()
		tec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TrackedEventCreate) check() error {
	if _, ok := tec.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "TrackedEvent.event_id"`)}
	}
	if _, ok := tec.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TrackedEvent.name"`)}
	}
	return nil
}

func (tec *TrackedEventCreate) sqlSave(ctx context.Context) (*TrackedEvent, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TrackedEventCreate) createSpec() (*TrackedEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &TrackedEvent{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(trackedevent.Table, sqlgraph.NewFieldSpec(trackedevent.FieldID, field.TypeUUID))
	)
	if id, ok := tec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tec.mutation.EventID(); ok {
		_spec.SetField(trackedevent.FieldEventID, field.TypeInt, value)
		_node.EventID = value
	}
	if value, ok := tec.mutation.Name(); ok {
		_spec.SetField(trackedevent.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// TrackedEventCreateBulk is the builder for creating many TrackedEvent entities in bulk.
type TrackedEventCreateBulk struct {
	config
	err      error
	builders []*TrackedEventCreate
}

// Save creates the TrackedEvent entities in the database.
func (tecb *TrackedEventCreateBulk) Save(ctx context.Context) ([]*TrackedEvent, error) {
	if tecb.err != nil {
		return nil, tecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*TrackedEvent, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrackedEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TrackedEventCreateBulk) SaveX(ctx context.Context) []*TrackedEvent {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TrackedEventCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TrackedEventCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
