// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// HighlightedComment is the predicate function for highlightedcomment builders.
type HighlightedComment func(*sql.Selector)

// TrackedEvent is the predicate function for trackedevent builders.
type TrackedEvent func(*sql.Selector)
